ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  host: longhorn.ayanides.cloud
  path: /

persistence:
  defaultClassReplicaCount: 3
  defaultClass: false

defaultSettings:
  storageMinimalAvailablePercentage: 10