ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: longhorn.ayanides.cloud
  path: /
  tls: true
  tlsSecret: longhorn-tls

persistence:
  defaultClassReplicaCount: 3
  defaultClass: false