applications:

# BUZZER
  buzzer:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: buzzer
    destination:
      namespace: buzzer
      server: https://kubernetes.default.svc
    project: apps
    source:
      repoURL: git@github.com:thibaultserti/kubernetes.git
      path: services/buzzer
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
