applications:
# CTFD
  ctfd:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: ctfd
    destination:
      namespace: ctfd
      server: https://kubernetes.default.svc
    project: apps
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: ctfd
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
