upgradeCompatibility: 1.13.4

hubble:
  enabled: true

  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
      - icmp
      - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true

  tls:
    enabled: false

  relay:
    enabled: true
    prometheus:
      enabled: true
      port: 9966
      serviceMonitor:
        enabled: true

  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      className: "traefik"
      hosts:
        - hubble.ayanides.cloud
      tls:
        - secretName: hubble-tls
          hosts:
            - hubble.ayanides.cloud


# -- Configure prometheus metrics on the configured port at /metrics
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

  # -- Metrics that should be enabled or disabled from the default metric list.
  # The list is expected to be separated by a space. (+metric_foo to enable
  # metric_foo , -metric_bar to disable metric_bar).
  # ref: https://docs.cilium.io/en/stable/observability/metrics/
  metrics: ~

# Preflight checks
#agent: false

# Preflight checks
operator:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

preflight:
  enabled: false
