# ALERTMANAGER
alertmanager:
  enabled: true

  serviceMonitor:
    selfMonitor: true

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - alertmanager.ayanides.cloud
    path: "/"
    pathType: Prefix
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.ayanides.cloud

  alertmanagerSpec:
    resources:
      requests:
        cpu: 11m
        memory: 53M
      limits:
        memory: 53M
    alertmanagerConfiguration:
      name: kube-prometheus-stack-alertmanagerconfig
    volumeMounts:
      - mountPath: /mnt/secrets-store
        name: secrets-store-inline
    volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: alertmanager