# GRAFANA
grafana:
  enabled: true

  serviceMonitor:
    enabled: true

  serviceAccount:
    create: true
    name: grafana

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - grafana.ayanides.cloud
    path: "/"
    pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.ayanides.cloud

  grafana.ini:
    smtp:
      enabled: false

  plugins:
    - grafana-piechart-panel

  admin:
    existingSecret: grafana-secret
    userKey: admin-user
    passwordKey: admin-password

  extraSecretMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "grafana"

  persistence:
    enabled: true
    size: 5Gi

  sidecar:
  # Managed by Terraform
    datasources:
      enabled: false
    notifiers:
      enabled: false
    dashboards:
      enabled: false


    annotations: {}
    multicluster:
      global:
        enabled: false
      etcd:
        enabled: false
