# GRAFANA
grafana:
  enabled: true

  useStatefulSet: true
  serviceMonitor:
    enabled: true

  podAnnotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-status: 'update'
    vault.hashicorp.com/role: 'grafana'
    vault.hashicorp.com/agent-inject-secret-user.env: 'secrets/data/grafana'
    vault.hashicorp.com/agent-inject-template-user.env: |
      {{ with secret "secrets/data/grafana" -}}
        export GF_SECURITY_ADMIN_USER={{ .Data.data.user }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-password.env: 'secrets/data/grafana'
    vault.hashicorp.com/agent-inject-template-password.env: |
      {{ with secret "secrets/data/grafana" -}}
        export GF_SECURITY_ADMIN_PASSWORD={{ .Data.data.password }}
      {{- end }}
  serviceAccount:
    create: true
    name: grafana

  command: ['sh', '-c']
  args: ['source /vault/secrets/*.env && grafana server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --packaging=docker cfg:default.log.mode=console cfg:default.paths.data=/var/lib/grafana/ cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning']

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - grafana.ayanides.cloud
    path: "/"
    pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.ayanides.cloud

  grafana.ini:
    server:
      domain: grafana.ayanides.cloud
      root_url: https://%(domain)s/
    smtp:
      enabled: false

  plugins:
    - grafana-piechart-panel

  env:
    GF_SECURITY_ADMIN_USER: admin
    GF_SECURITY_ADMIN_PASSWORD__FILE: /vault/secrets/password

  persistence:
    enabled: true
    size: 5Gi

  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      defaultDatasourceEnabled: false
    notifiers:
      enabled: true
      label: grafana_notifier
      labelValue: "1"
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folderAnnotation: grafana-dashboard-folder
      provider:
        foldersFromFilesStructure: true
        allowUiUpdates: false

    annotations: {}
    multicluster:
      global:
        enabled: false
      etcd:
        enabled: false
