# GRAFANA
grafana:
  enabled: true

  useStatefulSet: true
  serviceMonitor:
    enabled: true

  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'grafana'
    vault.hashicorp.com/agent-inject-template-config: |
      {{ with secret "secret/data/grafana" -}}
        export GF_SECURITY_ADMIN_USER="{{ .Data.data.user }}"
        export GF_SECURITY_ADMIN_PASSWORD="{{ .Data.data.password }}"
      {{- end }}
  serviceAccount:
    create: true
    name: grafana

    command: ['sh', '-c']
    args: ['source /vault/secrets/config']

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - grafana.ayanides.cloud
    path: "/"
    pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.ayanides.cloud

  grafana.ini:
    server:
      domain: grafana.ayanides.cloud
      root_url: https://%(domain)s/
    smtp:
      enabled: false
  plugins:
    - grafana-piechart-panel

  persistence:
    enabled: true
    size: 5Gi

  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      defaultDatasourceEnabled: false
    notifiers:
      enabled: true
      label: grafana_notifier
      labelValue: "1"
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folderAnnotation: grafana-dashboard-folder
      provider:
        foldersFromFilesStructure: true
        allowUiUpdates: false

    annotations: {}
    multicluster:
      global:
        enabled: false
      etcd:
        enabled: false