
# PROMETHEUS-OPERATOR
prometheusOperator:
  enabled: true
  serviceMonitor:
    selfMonitor: true

# PROMETHEUS
prometheus:
  enabled: true

  serviceMonitor:
    selfMonitor: true

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - prometheus.ayanides.cloud
    path: "/"
    pathType: Prefix
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.ayanides.cloud


  prometheusSpec:
    # look for CRD on the whole cluster
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    additionalScrapeConfigs:
      - job_name: kubernetes-node-exporter
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        scheme: https
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - source_labels: [__address__]
          regex: ^(.*):\d+$
          target_label: __address__
          replacement: $1:9100
        - target_label: __scheme__
          replacement: http
        # Host name
        - source_labels: [__meta_kubernetes_node_name]
          target_label: instance
