---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.default_issuer_name_staging }}
spec:
  acme:
    server: {{ .Values.server_staging }}
    email: {{ .Values.acme_registration_email }}
    privateKeySecretRef:
      name: {{ .Values.secret_reference_staging }}
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.default_issuer_name_prod }}
spec:
  acme:
    server: {{ .Values.server_prod }}
    email: {{ .Values.acme_registration_email }}
    privateKeySecretRef:
      name: {{ .Values.secret_reference_prod }}
    solvers:
      - http01:
          ingress:
            class: nginx
