replicaCount: 1


image:
  repository: ghcr.io/thibaultserti/rideshare
  pullPolicy: Always
  tag: 1.1.0

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod

  hosts:
    - host: fastapi-profiling-demo.ayanides.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fastapi-profiling-demo-tls
      hosts:
        - fastapi-profiling-demo.ayanides.cloud

autoscaling:
  enabled: false

serviceMonitor:
  enabled: true

env:
  - name: APP_NAME
    value: fastapi-profiling-example
  - name: PYROSCOPE_ENDPOINT
    value: http://pyroscope.monitoring:4040

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000


resources: {}
