replicaCount: 1

# podAnnotations:
#   policy.cilium.io/proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>,<Ingress/8000/TCP/HTTP>"

image:
  repository: ghcr.io/thibaultserti/efficom-challenge-01
  pullPolicy: Always
  tag: 1.2.0

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod

  hosts:
    - host: challenges.ayanides.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: challenges-tls
      hosts:
        - challenges.ayanides.cloud

autoscaling:
  enabled: false


env:
  - name: REDIS_HOST
    value: redis-master
  - name: REDIS_PORT
    value: "6379"


podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000


resources: {}
