default_install_hook_types:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        exclude: /secrets
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
      - id: check-yaml
        args:
          - --allow-multiple-documents
        exclude: /templates
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: check-shebang-scripts-are-executable
        stages: [commit]
