apiVersion: apps/v1
kind: Deployment
metadata:
  name: robusta-secret-init
  labels:
    app: robusta-secret-init
spec:
  selector:
    matchLabels:
      app: robusta-secret-init
  replicas: 1
  template:
    metadata:
      labels:
        app: robusta-secret-init
    spec:
      serviceAccountName: robusta-runner-service-account
      containers:
        - name: init
          image: busybox
          command: ["/bin/sh", "-ec", "sleep infinity"]
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: robusta
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          memory: 105M