applications:
  kube-state-metrics:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: monitoring
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-state-metrics
        targetRevision: 5.20.1
        helm:
          valueFiles:
          - $values/monitoring/kube-state-metrics/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true