

applications:

# K8S SIGS
  metrics-server:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: kube-system
    destination:
      namespace: kube-system
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://kubernetes-sigs.github.io/metrics-server
        chart: metrics-server
        targetRevision: 3.12.1
        helm:
          valueFiles:
          - $values/utils/metrics-server/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
