apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-observability-example.fullname" . }}-c
  labels:
    {{- include "fastapi-observability-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fastapi-observability-example.selectorLabels" . | nindent 4 }}
