# Only mandatory when there kubelet has not serverTLSBootsrap: true
# and when there is no kubelet-csr-approver process

# args:
#   - --kubelet-insecure-tls

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    memory: 105M