{{- range $secretStore := .Values.secretsStores }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $secretStore.name }}
  namespace: {{ $secretStore.namespace }}
spec:
  provider: vault
  secretObjects:
{{- range $secretName, $bindings := $secretStore.secrets }}
  - data:
{{- range $binding := $bindings }}
    - key: {{ $binding.kubernetesSecretKey }}
      objectName: {{ $secretStore.name }}-{{ $binding.vaultSecretKey }}
{{- end }}
    secretName: {{ $secretName }}
    type: Opaque
{{- end }}
  parameters:
    vaultAddress: {{ $.Values.vaultAddress }}
    roleName: {{ $secretStore.roleName }}
    objects: |
{{- range $bindings := $secretStore.secrets }}
{{- range $binding := $bindings }}
      - objectName: {{ $secretStore.name }}-{{ $binding.vaultSecretKey }}
        secretPath: {{ $binding.vaultSecretPath }}
        secretKey: {{ $binding.vaultSecretKey }}
{{- end }}
{{- end }}
{{- end }}
