controller:
  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      memory: 105M

speaker:
  resources:
    requests:
      cpu: 11m
      memory: 50M
    limits:
      memory: 50M
  frr:
    resources:
      requests:
        cpu: 11m
        memory: 37M
      limits:
        memory: 37M
  reloader:
    resources:
      requests:
        cpu: 11m
        memory: 27M
      limits:
        memory: 27M
  frrMetrics:
    resources:
      requests:
        cpu: 23m
        memory: 50M
      limits:
        memory: 50M