global:
  serverTelemetry:
    prometheusOperator: true

injector:
  enabled: false
  metrics:
    enabled: true


server:
  dataStorage:
    enabled: true

  auditStorage:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: vault.ayanides.cloud
        paths:
          - /
    pathType: Prefix
    tls:
      - secretName: vault-tls
        hosts:
          - vault.ayanides.cloud



  standalone:
    enabled: "true"

    # Note: Configuration files are stored in ConfigMaps so sensitive data
    # such as passwords should be either mounted through extraSecretEnvironmentVars
    # or through a Kube secret.  For more information see:
    # https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        # Enable unauthenticated metrics access (necessary for Prometheus Operator)
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }
      storage "file" {
        path = "/vault/data"
      }

      # Example configuration for using auto-unseal, using Google Cloud KMS. The
      # GKMS keys must already exist, and the cluster must have a service account
      # that is authorized to access GCP KMS.
      #seal "gcpckms" {
      #   project     = "vault-helm-dev"
      #   region      = "global"
      #   key_ring    = "vault-helm-unseal-kr"
      #   crypto_key  = "vault-helm-unseal-key"
      #}

      # Example configuration for enabling Prometheus metrics in your config.
      telemetry {
       prometheus_retention_time = "24h"
       disable_hostname = true
      }


# Vault UI
ui:
  enabled: true

# secrets-store-csi-driver-provider-vault
csi:
  enabled: true


serverTelemetry:
  serviceMonitor:
    enabled: true
  prometheusRules:
      enabled: true
      rules:
       - alert: vault-HighResponseTime
         annotations:
           message: The response time of Vault is over 500ms on average over the last 5 minutes.
         expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 500
         for: 5m
         labels:
           severity: warning
       - alert: vault-HighResponseTime
         annotations:
           message: The response time of Vault is over 1s on average over the last 5 minutes.
         expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 1000
         for: 5m
         labels:
           severity: critical