driver:
  enabled: true

collectors:
  enabled: true

tty: true

falco:
  rules_file:
    - /etc/falco/falco_rules.yaml #https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/k8s_audit_rules.yaml # https://github.com/falcosecurity/plugins/blob/master/plugins/k8saudit/rules/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  load_plugins: [k8saudit, json]
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config:
        ""
      open_params: "http://:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  json_output: true
  json_include_output_property: true
  priority: warning
  metrics:
    enabled: false
  grpc:
    enabled: true
  grpc_output:
    enabled: true
  syscall_event_drops:
    actions:
      - log
  http_output:
    enabled: true
    insecure: true
    url: "http://falcosidekick:2801/"

falcoctl:
  config:
    artifact:
      install:
        refs: [falco-rules:2,k8saudit-rules:0.6]
      follow:
        refs: [falco-rules:2,k8saudit-rules:0.6]

services:
  - name: k8saudit-webhook
    type: NodePort
    ports:
      - port: 9765
        nodePort: 30007
        protocol: TCP

customRules:
  rules-override.yaml: |-
    - list: user_known_sa_list
      items: [
        cilium-operator,
        cilium,
        coredns,
        kube-proxy,
        secrets-store-csi-driver,
        kubelet-csr-approver,
        kube-proxy,
        kube-state-metrics,
        metrics-server,
        hubble-ui,
        hubble-relay,
        attachdetach-controller,
        expand-controller
      ]

    - list: user_allowed_kube_namespace_image_list
      items: [
        registry.k8s.io/kube-state-metrics/kube-state-metrics,
        registry.k8s.io/sig-storage/csi-node-driver-registrar,
        registry.k8s.io/metrics-server/metrics-server,
        ghcr.io/postfinance/kubelet-csr-approver,
        registry.k8s.io/coredns/coredns,
        quay.io/cilium/cilium,
        quay.io/cilium/operator-generic,
        quay.io/cilium/hubble-relay,
        quay.io/cilium/hubble-ui
      ]

    - list: falco_privileged_images
      items: [
        docker.io/falcosecurity/falco-no-driver,
        docker.io/falcosecurity/falcoctl,
        quay.io/cilium/cilium,
        registry.k8s.io/kube-proxy
        registry.k8s.io/sig-storage/csi-node-driver-registrar,
        longhornio/longhorn-engine,
        longhornio/csi-node-driver-registrar,
        longhornio/longhorn-manager,
        longhornio/longhorn-instance-manager,
        quay.io/sustainable_computing_io/kepler
      ]

    # ignore get secrets
    - macro: consider_activity_events
      condition: (not (secret and kget))
