driver:
  enabled: true

collectors:
  enabled: true

tty: true

resources:
  requests:
    cpu: 296m
    memory: 1103M
  limits:
    memory: 1103M

falco:
  rules_file:
    - /etc/falco/falco_rules.yaml # https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/k8s_audit_rules.yaml # https://github.com/falcosecurity/plugins/blob/master/plugins/k8saudit/rules/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  load_plugins: [k8saudit, json]
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config:
        ""
      open_params: "http://:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  json_output: true
  json_include_output_property: true
  priority: warning
  metrics:
    enabled: false
  grpc:
    enabled: true
  grpc_output:
    enabled: true
  syscall_event_drops:
    actions:
      - log
  http_output:
    enabled: true
    insecure: true
    url: "http://falcosidekick:2801/"

falcoctl:
  config:
    artifact:
      install:
        refs: [falco-rules:2,k8saudit-rules:0.6]
      follow:
        refs: [falco-rules:2,k8saudit-rules:0.6]
        resources:
          requests:
            cpu: 11m
            memory: 53M
          limits:
            cpu: 11m
            memory: 53M

services:
  - name: k8saudit-webhook
    type: NodePort
    ports:
      - port: 9765
        nodePort: 30007
        protocol: TCP

customRules:
  rules-override.yaml: |-
    - list: user_known_sa_list
      items: [
        cilium-operator,
        cilium,
        coredns,
        kube-proxy,
        secrets-store-csi-driver,
        secrets-store-csi-driver-upgrade-crds,
        secrets-store-csi-driver-keep-crds,
        kubelet-csr-approver,
        kube-proxy,
        kube-state-metrics,
        metrics-server,
        hubble-ui,
        hubble-relay,
        attachdetach-controller,
        expand-controller,
        clusterrole-aggregation-controller,
        default,
        bootstrap-signer
      ]

    - list: user_allowed_kube_namespace_image_list
      items: [
        registry.k8s.io/kube-state-metrics/kube-state-metrics,
        registry.k8s.io/sig-storage/csi-node-driver-registrar,
        registry.k8s.io/csi-secrets-store/driver-crds,
        registry.k8s.io/metrics-server/metrics-server,
        ghcr.io/postfinance/kubelet-csr-approver,
        registry.k8s.io/coredns/coredns,
        quay.io/cilium/cilium,
        quay.io/cilium/operator-generic,
        quay.io/cilium/hubble-relay,
        quay.io/cilium/hubble-ui,
        quay.io/cilium/hubble-ui-backend,
        ghcr.io/ahrtr/etcd-defrag
      ]

    - list: falco_privileged_images
      items: [
        docker.io/falcosecurity/falco-no-driver,
        docker.io/falcosecurity/falcoctl,
        quay.io/cilium/cilium,
        registry.k8s.io/kube-proxy
        registry.k8s.io/sig-storage/csi-node-driver-registrar,
        registry.k8s.io/sig-storage/livenessprobe
        registry.k8s.io/csi-secrets-store/driver,
        registry.k8s.io/csi-secrets-store/livenessprobe,
        longhornio/longhorn-engine,
        longhornio/csi-node-driver-registrar,
        longhornio/longhorn-manager,
        longhornio/longhorn-instance-manager,
        quay.io/sustainable_computing_io/kepler,
        registry.k8s.io/sig-storage/csi-node-driver-registrar

      ]

    # ignore get secrets
    - macro: consider_activity_events
      condition: (not (secret and kget))


    - list: falco_hostnetwork_images
      items: [
        gcr.io/google-containers/prometheus-to-sd,
        gcr.io/projectcalico-org/typha,
        gcr.io/projectcalico-org/node,
        gke.gcr.io/gke-metadata-server,
        gke.gcr.io/kube-proxy,
        gke.gcr.io/netd-amd64,
        k8s.gcr.io/ip-masq-agent-amd64,
        k8s.gcr.io/prometheus-to-sd,
        registry.k8s.io/ip-masq-agent-amd64,
        registry.k8s.io/prometheus-to-sd,
        quay.io/cilium/operator-generic,
        quay.io/metallb/speaker,
        quay.io/frrouting/frr,
        ghcr.io/ahrtr/etcd-defrag,
        registry.k8s.io/kube-apiserver,
      ]

    - list: falco_hostpid_images
      items: [
        longhornio/longhorn-manager
      ]

    - list: falco_sensitive_mount_images
      items: [
        otel/opentelemetry-collector-contrib,
        quay.io/sustainable_computing_io/kepler,
        quay.io/prometheus/node-exporter,
        longhornio/longhorn-instance-manager
      ]

    # a placeholder for whitelist log files that could be cleared. Recommend the macro as (fd.name startswith "/var/log/app1*")
    # to remove when falco rule 2.1.0 is released
    - macro: allowed_clear_log_files
      condition: (proc.name=containerd and (fd.name startswith "/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/" or
                                        fd.name startswith "/var/lib/containerd/tmpmounts/"))