driver:
  enabled: true
  kind: modern-bpf

falco:
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  load_plugins: [k8saudit, json]
  json_output: true
  json_include_output_property: true
  priority: warning
  metrics:
    enabled: true

  # Publish to falco sidekick
  http_output:
    enabled: true
    insecure: true
    url: "http://falcosidekick:2801/"
