loki:

  auth_enabled: false

  serviceAccount:
    name: loki

  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory

  ingester:
    chunk_idle_period: 30m
    max_chunk_age: 1h
    chunk_target_size: 1572864

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
    type: s3
    s3:
      endpoint: http://minio.minio:9000
      s3ForcePathStyle: true
      insecure: true

  compactor:
    working_directory: /var/loki/compactor
    shared_store: s3
    retention_enabled: true

  frontend:
    max_outstanding_per_tenant: 2048
    compress_responses: true
    log_queries_longer_than: 20s

  query_scheduler:
    max_outstanding_requests_per_tenant: 2048
    grpc_client_config:
      max_send_msg_size: 33554432
      max_recv_msg_size: 33554432

  limits_config:
    split_queries_by_interval: 0
    retention_period: 744h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      shared_store: s3
      cache_ttl: 24h
    aws:
      endpoint: http://minio.minio:9000
      insecure: true

ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - loki.ayanides.cloud
  tls:
    - secretName: loki-tls
      hosts:
        - loki.ayanides.cloud


singleBinary:
  replicas: 1
  extraArgs:
    - '-config.expand-env=true'
    - '-tracing.enabled=true'
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_SECRET_ACCESS_KEY

    - name: JAEGER_AGENT_HOST
      value: otel-collector.monitoring
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"

  persistence:
    storageClass: "default"
    size: 10Gi

  extraVolumeMounts:
    - mountPath: /mnt/secrets-store
      name: secrets-store-inline
  extraVolumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: loki

test:
  enabled: false

monitoring:
  dashboards:
    enabled: false

  # Recording rules for monitoring Loki, required for some dashboards
  rules:
    enabled: true
    alerting: true

  serviceMonitor:
    enabled: true

  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
