fullnameOverride: node-exporter
prometheus:
  monitor:
    enabled: true
    relabelings:
    - action: replace
      sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: nodename
    - sourceLabels: [job]
      targetLabel: job
      action: replace
      replacement: node-exporter

    interval: 30s

# resources:
#   requests:
#     cpu: 15m
#     memory: 105M
#   limits:
#     memory: 105M