ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: In-Cluster eBPF monitoring
    gethomepage.dev/pod-selector: >-
            app.kubernetes.io/name in (
                hubble-ui,
                hubble-relay
            )
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/grafana/pyroscope@main/images/logo.png?raw=true
    gethomepage.dev/name: Pyroscope
    gethomepage.dev/weight: "40"
  hosts:
    - pyroscope.ayanides.cloud
serviceMonitor:
  enabled: true

# pyroscope:
#   resources:
#     requests:
#       cpu: 23m
#       memory: 443M
#     limits:
#       memory: 443M

# agent:
#   resources:
#     requests:
#       cpu: 23m
#       memory: 164M
#     limits:
#       memory: 164M

#   configReloader:
#     resources:
#       requests:
#         cpu: 11m
#         memory: 53M
#       limits:
#         memory: 53M