ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - pyroscope.ayanides.cloud


serviceMonitor:
  enabled: true

# pyroscope:
#   resources:
#     requests:
#       cpu: 23m
#       memory: 443M
#     limits:
#       memory: 443M

# agent:
#   resources:
#     requests:
#       cpu: 23m
#       memory: 164M
#     limits:
#       memory: 164M

#   configReloader:
#     resources:
#       requests:
#         cpu: 11m
#         memory: 53M
#       limits:
#         memory: 53M