ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: pyroscope.ayanides.cloud
      paths:
      - path: /
        pathType: Prefix
  tls:
   - secretName: pyroscope-tls
     hosts:
       - pyroscope.ayanides.cloud
