applications:
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: 5.36.7
        helm:
          valueFiles:
          - $values/argocd/values.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argocd-apps
        targetRevision: 1.2.0
        helm:
          valueFiles:
          - $values/argocd-apps/values.yaml
          - $values/argocd-apps/cilium.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
projects:
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
  - name: system
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Kube-System Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: kube-system
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false