applications:
  # ARGOCD
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: 5.36.7
        helm:
          valueFiles:
          - $values/argocd/values.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - kind: Secret
        name: argocd-secret
        namespace: argocd
        jsonPointers:
          - /data
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argocd-apps
        targetRevision: 1.2.0
        helm:
          valueFiles:
          - $values/argocd-apps/values.yaml
          - $values/argocd-apps/projects.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true

  # NETWORK
  - name: cilium
    namespace: argocd
    destination:
      namespace: kube-system
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://helm.cilium.io
        chart: cilium
        targetRevision: 1.13.4
        helm:
          valueFiles:
          - $values/cilium/values.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - kind: Secret
        name: cilium-ca
        namespace: kube-system
        jsonPointers:
          - /data
      - kind: Secret
        name: hubble-ca-secret
        namespace: kube-system
        jsonPointers:
          - /data
      - kind: Secret
        name: hubble-server-certs
        namespace: kube-system
        jsonPointers:
          - /data
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  - name: cert-manager
    namespace: argocd
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: 1.12.2
        helm:
          valueFiles:
          - $values/cert-manager/values.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: cluster-issuer
    namespace: argocd
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        path: cluster-issuer
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: metallb
    namespace: argocd
    destination:
      namespace: metallb
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://metallb.github.io/metallb
        chart: metallb
        targetRevision: 0.13.10
        helm:
          valueFiles:
          - $values/metallb/values.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
      - kind: CustomResourceDefinition
        name: addresspools.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  - name: traefik
    namespace: argocd
    destination:
      namespace: traefik
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://traefik.github.io/charts
        chart: traefik
        targetRevision: 23.1.0
        helm:
          valueFiles:
          - $values/traefik/values.yaml
      - repoURL: https://github.com/thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
