ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: status.ayanides.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific

# resources:
#   requests:
#     cpu: 100m
#     memory: 128Mi

volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 4Gi
  storageClassName: longhorn


serviceMonitor:
  enabled: false
  interval: 1m
