cluster:
  name: belt


k8sServiceHost: 192.168.1.10
k8sServicePort: 6443

kubeProxyReplacement: true
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16

bpf:
  vlanBypass: 0

hubble:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 11m
  #     memory: 53M
  #   limits:
  #     memory: 53M
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - icmp
      - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace"
      - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
    enableOpenMetrics: true
    serviceMonitor:
      enabled: false

  tls:
    enabled: true

  relay:
    enabled: true
    # resources:
    #   requests:
    #     cpu: 15m
    #     memory: 105M
    #   limits:
    #     memory: 105M
    prometheus:
      enabled: true
      port: 9966
      serviceMonitor:
        enabled: false

  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: In-Cluster eBPF monitoring
        gethomepage.dev/pod-selector: >-
                app.kubernetes.io/name in (
                    hubble-ui,
                    hubble-relay
                )
        gethomepage.dev/group: Monitoring
        gethomepage.dev/icon: cilium.png
        gethomepage.dev/name: Hubble
        gethomepage.dev/weight: "50"
      className: "traefik"
      hosts:
        - hubble.ayanides.cloud



# -- Configure prometheus metrics on the configured port at /metrics
prometheus:
  enabled: true
  serviceMonitor:
    enabled: false



operator:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 105M
  #   limits:
  #     memory: 105M
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false
