apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-image-pull-policy
spec:
  rules:
    - name: setRevisionHistoryLimit
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - StatefulSet
            - DaemonSet
      mutate:
        patchStrategicMerge:
          spec:
            revisionHistoryLimit: 2
