serviceAccount:
  create: true
  name: kured

extraEnvVars:
  - name: KURED_NOTIFY_URL
    valueFrom:
      secretKeyRef:
        name: kured
        key: discord_url


volumeMounts:
- mountPath: /mnt/secrets-store
  name: secrets-store-inline

volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: kured


configuration:
  useRebootSentinelHostPath: true
  metricsHost: "0.0.0.0"
  metricsPort: 8080
  alertFilterRegexp: "^(CPUThrottlingHigh|InfoInhibitor|Watchdog|etcdHighNumberOfFailedGRPCRequests|etcdHighCommitDurations)$"
  alertFiringOnly: true
  startTime: "00:00"
  endTime: "06:00"
  timeZone: "Europe/Paris"
  period: "0h30m0s"
  forceReboot: true
  prometheusUrl: "http://vmsingle-vm-stack-victoria-metrics-k8s-stack.monitoring.svc:8429"
  rebootDays: [mo,tu,we,th,fr]
  rebootSentinel: "/var/run/reboot-required"
  rebootCommand: "/bin/systemctl reboot"
  annotateNodes: true
  lockTtl: 3600"
  lockReleaseDelay: 600
  drainTimeout: 1200
  drainGracePeriod: 600
  preferNoScheduleTaint: "weave.works/kured-node-reboot"
  logFormat: "json"
  concurrency: 1


metrics:
  create: true

service:
  create: true
  port: 8080
