apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/instance: monitoring.otel
  endpoints:
    - port: monitoring
  namespaceSelector:
    matchNames:
      - monitoring
