# GLOBAL
global:
  logging:
    format: text
    level: info

# CONFIGS

configs:
  cm:
    admin.enabled: true
    exec.enabled: false
    server.rbac.log.enforce.enable: false
    #dex.config
    #oidc.config

  params:
    otlp.adress: ""
    server.insecure: true

  rbac:
    policy.default: ""
    policy.csv: ""
    scopes: "[groups]"

  ssh:
    extraHosts: ""

  secret:
    # htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/
    argocdServerAdminPassword: "$2a$10$tCwP269.mLFpDZjhXqtRt.0038jDzPAoLX8Hkj33idrfC0se9Ab9a"

# CONTROLLER

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false #true
    rules:
      enabled: false #true

# DEX

dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false #true

# REDIS

redis:
  exporter:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false #true

# SERVER

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false #true
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - argocd.ayanides.cloud
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.ayanides.cloud
    https: false

# REPOSERVER

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false #true

# APPLICATIONSET

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false #true

# NOTIFICATIONS

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false #true
