existingObjstoreSecret: thanos-objstore-secret

query:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 105M
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hostname: thanos.ayanides.cloud
    path: "/"
    pathType: Prefix

  replicaLabel:
    - prometheus_replica
    - rule_replica
  dnsDiscovery:
    sidecarsService: prometheus-stack-kube-prom-thanos-discovery
    sidecarsNamespace: monitoring

  extraFlags:
    - |
      --tracing.config=type: OTLP
      config:
        service_name: "thanos-query"
        client_type: http
        endpoint: "otel-collector.monitoring:4318"
        insecure: true

  extraVolumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: thanos

  extraVolumeMounts:
    - mountPath: /mnt/secrets-store
      name: secrets-store-inline

queryFrontend:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 105M
  #   limits:
  #     memory: 105M
  extraFlags:
    - |
      --tracing.config=type: OTLP
      config:
        service_name: "thanos-query-frontend"
        client_type: http
        endpoint: "otel-collector.monitoring:4318"
        insecure: true

bucketweb:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 105M
  #   limits:
  #     memory: 105M
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hostname: thanos-bucketweb.ayanides.cloud
    path: "/"
    pathType: Prefix
  extraFlags:
    - |
      --tracing.config=type: OTLP
      config:
        service_name: "thanos-bucketweb"
        client_type: http
        endpoint: "otel-collector.monitoring:4318"
        insecure: true

compactor:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 23m
  #     memory: 2408M
  persistence:
    storageClass: default
    size: 100Gi
  retentionResolutionRaw: 7d # min 40h
  retentionResolution5m: 14d # min 10d
  retentionResolution1h: 30d # min 10d

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hostname: thanos-compactor.ayanides.cloud
    path: "/"
    pathType: Prefix

  extraFlags:
    - |
      --tracing.config=type: OTLP
      config:
        service_name: "thanos-compactor"
        client_type: http
        endpoint: "otel-collector.monitoring:4318"
        insecure: true


storegateway:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 250M
  persistence:
    storageClass: default
    size: 10Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hostname: thanos-storegateway.ayanides.cloud
    path: "/"
    pathType: Prefix

  extraFlags:
    - |
      --tracing.config=type: OTLP
      config:
        service_name: "thanos-storegateway"
        client_type: http
        endpoint: "otel-collector.monitoring:4318"
        insecure: true

ruler:
  enabled: false

receive:
  enabled: false

receiveDistributor:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
