existingObjstoreSecret: thanos-objstore-secret

query:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostname: thanos.ayanides.cloud
    path: "/"
    pathType: Prefix
    tls: true

  replicaLabel:
    - prometheus_replica
    - rule_replica
  dnsDiscovery:
    sidecarsService: prometheus-stack-kube-prom-thanos-discovery
    sidecarsNamespace: monitoring

  extraVolumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: thanos

  extraVolumeMounts:
    - mountPath: /mnt/secrets-store
      name: secrets-store-inline

queryFrontend:
  enabled: true

bucketweb:
  enabled: true

compactor:
  enabled: true
  persistence:
    storageClass: default
    size: 100Gi
  retentionResolutionRaw: 7d
  retentionResolution5m: 30d
  retentionResolution1h: 90d

storegateway:
  enabled: true
  persistence:
    storageClass: longhorn
    size: 50Gi

ruler:
  enabled: false

receive:
  enabled: false

receiveDistributor:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
