{{- range $slo := .Values.slos_k8s }}
---
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: {{ $slo.name }}
spec:
  service: {{ $slo.name }}
  slos:
    - name: "requests-availability"
      objective: {{ $slo.objective }}
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        plugin:
          id: "sloth-common/traefik/v2/availability"
          options:
            service_name_regex: "^.*{{ $slo.name }}.*$"
      alerting:
        name: MyServiceHighErrorRate
        labels:
          category: "availability"
        annotations:
          summary: "High error rate on {{ $slo.name }} requests responses"
    - name: "requests-latency"
      objective: {{ $slo.objective }}
      description: "Common SLO based on latency for HTTP request."
      sli:
        plugin:
          id: "sloth-common/traefik/v2/latency"
          options:
            service_name_regex: "^.*{{ $slo.name }}.*$"
            bucket: "1"
            exclude_errors: "true"
      alerting:
        name: MyServiceHighLatency
        labels:
          category: "latency"
        annotations:
          summary: "High latency rate {{ $slo.name }} requests responses"
{{- end }}
