app:
  replicaCount: 1

  podAnnotations:
    instrumentation.opentelemetry.io/inject-python: "monitoring/instrumentation-python"
  #   policy.cilium.io/proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>,<Ingress/8000/TCP/HTTP>"

  image:
    repository: ghcr.io/thibaultserti/efficom-challenge-01
    pullPolicy: Always
    tag: 1.3.0

  serviceAccount:
    create: true

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    className: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - host: challenge.ayanides.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: challenges-tls
        hosts:
          - challenge.ayanides.cloud

  autoscaling:
    enabled: false


  env:
    - name: REDIS_HOST
      value: redis-master.redis
    - name: REDIS_PORT
      value: "6379"


  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000


  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      memory: 105M