
projects:
  argocd:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"

  system:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: System Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: kube-system
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: traefik
        server: https://kubernetes.default.svc
      - namespace: metallb
        server: https://kubernetes.default.svc
      - namespace: kubernetes-dashboard
        server: https://kubernetes.default.svc
      - namespace: longhorn-system
        server: https://kubernetes.default.svc
      - namespace: external-dns
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"

  vault:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Vault Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*" # secrets-stores
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"

  monitoring:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Monitoring Project
    clusterResourceBlacklist:
      - group: cilium.io
        kind: CiliumIdentity
    sourceRepos:
      - "*"
    destinations:
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: kube-system
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"

  minio:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Minio Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: minio
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false

  redis:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Minio Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: redis
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"

  kyverno:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Kyverno Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: kyverno
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"


  security:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Security Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: trivy
        server: https://kubernetes.default.svc
      - namespace: polaris
        server: https://kubernetes.default.svc
      - namespace: falco
        server: https://kubernetes.default.svc
      - namespace: tetragon
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"


  goldilocks:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: goldilocks Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: goldilocks
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"


  teleport:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Teleport Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: teleport
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"


  ctfd:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: CTFD Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: ctfd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"


  my-apps:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: My-apps Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: my-apps
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"

  example:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Example Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: opentelemetry-demo
        server: https://kubernetes.default.svc
      - namespace: example
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"

  services:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Services Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: yopass
        server: https://kubernetes.default.svc
      - namespace: stirling-pdf
        server: https://kubernetes.default.svc
      - namespace: homepage
        server: https://kubernetes.default.svc
      - namespace: buzzer
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
