
projects:
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
  - name: system
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: System Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: kube-system
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: traefik
        server: https://kubernetes.default.svc
      - namespace: metallb
        server: https://kubernetes.default.svc
      - namespace: kubernetes-dashboard
        server: https://kubernetes.default.svc
      - namespace: longhorn-system
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
  - name: vault
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Vault Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*" # secrets-stores
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
  - name: monitoring
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Monitoring
    sourceRepos:
      - "*"
    destinations:
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: kube-system
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false