applications:
  # ARGOCD
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: 5.42.0
        helm:
          valueFiles:
          - $values/argocd/argocd/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - kind: Secret
        name: argocd-secret
        namespace: argocd
        jsonPointers:
          - /data
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argocd-apps
        targetRevision: 1.4.1
        helm:
          valueFiles:
          - $values/argocd/argocd-apps/values.yaml
          - $values/argocd/argocd-apps/projects.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy: {}

  # CILIUM
  - name: cilium
    namespace: argocd
    destination:
      namespace: kube-system
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://helm.cilium.io
        chart: cilium
        targetRevision: 1.13.4
        helm:
          valueFiles:
          - $values/cilium/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - kind: Secret
        name: cilium-ca
        namespace: kube-system
        jsonPointers:
          - /data
      - kind: Secret
        name: hubble-ca-secret
        namespace: kube-system
        jsonPointers:
          - /data
      - kind: Secret
        name: hubble-server-certs
        namespace: kube-system
        jsonPointers:
          - /data
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

# CERT-MANAGER
  - name: cert-manager
    namespace: argocd
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.12.3
        helm:
          valueFiles:
          - $values/cert-manager/cert-manager/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: cluster-issuer
    namespace: argocd
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: cert-manager/cluster-issuer
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# METALLB
  - name: metallb
    namespace: argocd
    destination:
      namespace: metallb
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://metallb.github.io/metallb
        chart: metallb
        targetRevision: 0.13.10
        helm:
          valueFiles:
          - $values/metallb/metallb/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - kind: CustomResourceDefinition
        group: "apiextensions.k8s.io"
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
      - kind: CustomResourceDefinition
        group: "apiextensions.k8s.io"
        name: addresspools.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  - name: metallb-ipaddress-pool
    namespace: argocd
    destination:
      namespace: metallb
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: metallb/metallb-ipaddresspool
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# TRAEFIK
  - name: traefik
    namespace: argocd
    destination:
      namespace: traefik
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://traefik.github.io/charts
        chart: traefik
        targetRevision: 23.2.0
        helm:
          valueFiles:
          - $values/traefik/traefik/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: traefik-dashboard
    namespace: argocd
    destination:
      namespace: traefik
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: traefik/traefik-dashboard
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# K8S SIGS
  - name: metrics-server
    namespace: argocd
    destination:
      namespace: kube-system
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://kubernetes-sigs.github.io/metrics-server
        chart: metrics-server
        targetRevision: 3.10.0
        helm:
          valueFiles:
          - $values/k8s-sigs/metrics-server/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: kubernetes-dashboard
    namespace: argocd
    destination:
      namespace: kubernetes-dashboard
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://kubernetes.github.io/dashboard
        chart: kubernetes-dashboard
        targetRevision: 6.0.8
        helm:
          valueFiles:
          - $values/k8s-sigs/kubernetes-dashboard/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: secrets-store-csi-driver
    namespace: argocd
    destination:
      namespace: kube-system
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
        chart: secrets-store-csi-driver
        targetRevision: 1.3.4
        helm:
          valueFiles:
          - $values/k8s-sigs/secrets-store-csi-driver/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# LONGHORN
  - name: longhorn
    namespace: argocd
    destination:
      namespace: longhorn-system
      server: https://kubernetes.default.svc
    project: system
    sources:
      - repoURL: https://charts.longhorn.io
        chart: longhorn
        targetRevision: 1.5.1
        helm:
          valueFiles:
          - $values/longhorn/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# VAULT
  - name: vault
    namespace: argocd
    destination:
      namespace: vault
      server: https://kubernetes.default.svc
    project: vault
    sources:
      - repoURL: https://helm.releases.hashicorp.com
        chart: vault
        targetRevision: 0.25.0
        helm:
          valueFiles:
          - $values/vault/vault/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  - name: secrets-stores
    namespace: argocd
    destination:
      namespace: vault
      server: https://kubernetes.default.svc
    project: vault
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: vault/secrets-stores
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# KUBE-PROMETHEUS-STACK
  - name: prometheus-stack
    namespace: argocd
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 48.2.2
        helm:
          skipCrds: true
          valueFiles:
          - $values/monitoring/prometheus-stack/alertmanager.yaml
          - $values/monitoring/prometheus-stack/alertmanagerconfig.yaml
          - $values/monitoring/prometheus-stack/grafana.yaml
          - $values/monitoring/prometheus-stack/ksm.yaml
          - $values/monitoring/prometheus-stack/node-exporter.yaml
          - $values/monitoring/prometheus-stack/prometheus.yaml
          - $values/monitoring/prometheus-stack/promrules.yaml
          - $values/monitoring/prometheus-stack/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
          - '.webhooks[]?.failurePolicy'
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
          - '.webhooks[]?.failurePolicy'
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  - name: prometheus-stack-crds
    namespace: argocd
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    source:
      repoURL: https://github.com/prometheus-community/helm-charts.git
      path: charts/kube-prometheus-stack/charts/crds/
      directory:
        recurse: true
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - Replace=true
      automated:
        prune: true
        selfHeal: true

# EXPORTERS
  - name: blackbox-exporter
    namespace: argocd
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-blackbox-exporter
        targetRevision: 8.2.0
        helm:
          valueFiles:
          - $values/monitoring/blackbox-exporter/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: pihole-exporter
    namespace: argocd
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: monitoring/pihole-exporter
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# ROBUSTA

  - name: robusta
    namespace: argocd
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: https://robusta-charts.storage.googleapis.com
        chart: robusta
        targetRevision: 0.10.20
        helm:
          valueFiles:
          - $values/monitoring/robusta/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

  - name: robusta-secret-init
    namespace: argocd
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: monitoring/robusta-secret-init
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true

# MINIO
  - name: minio
    namespace: argocd
    destination:
      namespace: minio
      server: https://kubernetes.default.svc
    project: minio
    sources:
      - repoURL: registry-1.docker.io
        chart: bitnamicharts/minio
        targetRevision: 12.6.10
        helm:
          valueFiles:
          - $values/minio/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true