# controller:
#   resources:
#     requests:
#       cpu: 93m
#       memory: 105M
#     limits:
#       memory: 105M

vpa:
  enabled: true
  updater:
    enabled: false
  # admissionController:
  #   resources:
  #     requests:
  #       cpu: 15m
  #       memory: 105M
  #     limits:
  #       memory: 105M
  recommender:
    extraArgs:
      prometheus-address: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
      storage: prometheus
    # resources:
    #   requests:
    #     cpu: 15m
    #     memory: 105M
    #   limits:
    #     memory: 105M
dashboard:
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 105M
  #   limits:
  #     memory: 105M
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: goldilocks.ayanides.cloud
        paths:
          - path: /
            type: ImplementationSpecific
