projects:
  kyverno:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Kyverno Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: kyverno
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"