globalArguments:
  - "--global.checknewversion"

additionalArguments:
  - --serversTransport.insecureSkipVerify=true

logs:
  access:
    enabled: true
    format: json

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.100

ingressRoute:
  dashboard:
    enabled: true
providers:
  kubernetesIngress:
    allowExternalNameServices: true
    publishedService:
      enabled: true

ports:
  web:
    redirectTo: websecure
    forwardedHeaders:
      trustedIPs:
        - 192.168.0.0/16
        - 10.0.0.0/8
        - 172.16.0.0/12
    proxyProtocol:
      trustedIPs:
        - 192.168.0.0/16
        - 10.0.0.0/8
        - 172.16.0.0/12

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    serviceMonitor:
      metricRelabelings:
        - sourceLabels: [__name__]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik
      interval: 30s
      honorLabels: true
    prometheusRule:
      additionalLabels: {}
      rules:
        - alert: TraefikDown
          expr: up{job="traefik"} == 0
          for: 5m
          labels:
            context: traefik
            severity: warning
          annotations:
            summary: "Traefik Down"
            description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"