sendanonymoususage: false

logs:
  access:
    enabled: true

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.100

ingressRoute:
  dashboard:
    enabled: true
providers:
  kubernetesIngress:
    allowExternalNameServices: true
    publishedService:
      enabled: true

ports:
  web:
    redirectTo: websecure
    forwardedHeaders:
      trustedIPs:
        - "192.168.1.40/32" #Nginx