globalArguments:
  - "--global.checknewversion"

additionalArguments:
  - --serversTransport.insecureSkipVerify=true

image:
  repository: traefik
  tag: v3.0.3

logs:
  access:
    enabled: true
    format: json
    fields:
      defaultMode: keep
      headers:
        defaultMode: redact
        names:
          User-Agent: keep
          X-Forwarded-For: keep
          X-Forwarded-Server: keep
          X-Real-Ip: keep
          X-B3-Parentspanid: keep
          X-B3-Spanid: keep
          X-B3-Traceid: keep
          X-B3-Sampled: keep


service:
  annotations:
    io.cilium/lb-ipam-ips: "192.168.1.100"
    kube-vip.io/ignore: "true"

ingressRoute:
  dashboard:
    enabled: true
providers:
  kubernetesIngress:
    allowExternalNameServices: true
    publishedService:
      enabled: true

ports:
  web:
    redirectTo:
      port: websecure
    forwardedHeaders:
      trustedIPs:
        - 192.168.0.0/16
        - 10.0.0.0/8
        - 172.16.0.0/12
    proxyProtocol:
      trustedIPs:
        - 192.168.0.0/16
        - 10.0.0.0/8
        - 172.16.0.0/12
tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-cert

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    serviceMonitor:
      metricRelabelings:
        - sourceLabels: [__name__]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik
      interval: 30s
      honorLabels: true
    prometheusRule:
      additionalLabels: {}
      rules:
        - alert: TraefikDown
          expr: up{job="traefik"} == 0
          for: 5m
          labels:
            context: traefik
            severity: warning
          annotations:
            summary: "Traefik Down"
            description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

tracing:
  openTelemetry:
    address: otel-collector.monitoring:4318
    insecure: true

# resources:
#   requests:
#     cpu: 23m
#     memory: 164M
#   limits:
#     memory: 164M
