globalArguments:
  - "--global.checknewversion"

logs:
  access:
    enabled: true

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.100

ingressRoute:
  dashboard:
    enabled: true
providers:
  kubernetesIngress:
    allowExternalNameServices: true
    publishedService:
      enabled: true

ports:
  web:
    redirectTo: websecure
    forwardedHeaders:
#      insecure: true
      trustedIPs:
        - 192.168.0.0/16
        - 10.0.0.0/8
        - 172.16.0.0/12

additionalArguments:
  - --serversTransport.insecureSkipVerify=true
