ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: locust.ayanides.cloud
      pathType: ImplementationSpecific
      path: /
