ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: locust.ayanides.cloud
      pathType: ImplementationSpecific
      path: /
  tls:
    - secretName: locust-tls
      hosts:
        - locust.ayanides.cloud
