projects:
  traefik:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Traefik Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: kube-system
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: traefik
        server: https://kubernetes.default.svc
      - namespace: external-dns
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
