applications:
  external-dns:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: external-dns
    destination:
      namespace: external-dns
      server: https://kubernetes.default.svc
    project: traefik
    sources:
      - repoURL: https://kubernetes-sigs.github.io/external-dns/
        chart: external-dns
        targetRevision: 1.14.5
        helm:
          valueFiles:
          - $values/utils/external-dns/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
