applications:
  traefik:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: traefik
    destination:
      namespace: traefik
      server: https://kubernetes.default.svc
    project: traefik
    sources:
      - repoURL: https://traefik.github.io/charts
        chart: traefik
        targetRevision: 32.1.1
        helm:
          valueFiles:
          - $values/traefik/traefik/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true


  traefik-dashboard:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: traefik
    destination:
      namespace: traefik
      server: https://kubernetes.default.svc
    project: traefik
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: traefik/traefik-dashboard
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
