manager:
  # A full list of valud identifiers can be found here: https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/featuregate/featuregate.go
  featureGates: ""

  collectorImage:
    repository: "otel/opentelemetry-collector-contrib"

  serviceMonitor:
    enabled: true

  prometheusRule:
    enabled: false
    defaultRules: # WorkqueueDepth keep firing
      enabled: false

  # resources:
  #   requests:
  #     cpu: 11m
  #     memory: 64M
  #   limits:
  #     memory: 64M

admissionWebhooks:
  create: true
  certManager:
    enabled: true



# kubeRBACProxy:
#   resources:
#     requests:
#       cpu: 11m
#       memory: 53M
#     limits:
#       memory: 53M