manager:
  # A full list of valud identifiers can be found here: https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/featuregate/featuregate.go
  featureGates: ""

  serviceMonitor:
    enabled: true

  prometheusRule:
    enabled: false
    defaultRules: # WorkqueueDepth keep firing
      enabled: false

admissionWebhooks:
  create: true
  certManager:
    enabled: true
