operator:
  vulnerabilityScannerEnabled: false
  configAuditScannerEnabled: true
  rbacAssessmentScannerEnabled: true
  clusterComplianceEnabled: true
  vulnerabilityScannerScanOnlyCurrentRevisions: true
  configAuditScannerScanOnlyCurrentRevisions: true
  metricsFindingsEnabled: true
  metricsClusterComplianceInfo: true
  metricsVulnIdEnabled: true
  metricsImageInfo: true
  metricsConfigAuditInfo: true
  metricsRbacAssessmentInfo: true
  metricsInfraAssessmentInfo: true
  metricsExposedSecretInfo: true
  exposedSecretScannerEnabled: true
  webhookBroadcastURL: ""


serviceMonitor:
  enabled: true

trivyOperator:
  vulnerabilityReportsPlugin: "Trivy"
  configAuditReportsPlugin: "Trivy"

trivy:
  ignoreUnfixed: true
  # server:
  #   resources:
  #     requests:
  #       cpu: 23m
  #       memory: 866M
  #     limits:
  #       memory: 866M

  resources:
    requests:
      memory: 2000M
    limits:
      memory: 4000M
