operator:
  vulnerabilityScannerEnabled: false
  configAuditScannerEnabled: true
  rbacAssessmentScannerEnabled: true
  clusterComplianceEnabled: true
  vulnerabilityScannerScanOnlyCurrentRevisions: true
  metricsVulnIdEnabled: true
  configAuditScannerScanOnlyCurrentRevisions: true
  metricsFindingsEnabled: true
  exposedSecretScannerEnabled: true
  webhookBroadcastURL: ""


serviceMonitor:
  enabled: true

trivyOperator:
  vulnerabilityReportsPlugin: "Trivy"
  configAuditReportsPlugin: "Trivy"

trivy:
  ignoreUnfixed: true
  server:
    resources:
      requests:
        cpu: 23m
        memory: 866M
      limits:
        memory: 866M

  resources:
    requests:
      cpu: 100m
      memory: 750M
    limits:
      memory: 750M