image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.9.6

enableRbac: true

serviceAccount:
  name: homepage
  create: true



# Enable the ingress to expose Homepage to the network.
ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    ingressClassName: "traefik"
    hosts:
      - host: "home.ayanides.cloud"
        paths:
          - path: /
            pathType: Prefix


# All the config files for Homepage can be specified under their relevant config block.
config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks:
    - Networking:
        - Github:
            - icon: github.png
              href: https://github.com/thibaultserti/

        - LinkedIn:
            - icon: linkedin.png
              href: https://linkedin.com/in/thibault-ayanides/
  services:
    - Deployment:
        - Semaphore:
            href: https://semaphore.ayanides.cloud/
            siteMonitor: https://semaphore.ayanides.cloud/
            description: Manage servers with Ansible
            icon: semaphore.png
        - Terraform:
            href: https://app.terraform.io/app/thibaultserti/workspaces/
            siteMonitor: https://app.terraform.io/app/thibaultserti/workspaces/
            description: Manage services with Terraform
            icon: terraform.png
    - Monitoring: []
    - Network:
        - Pihole:
            href: https://pihole.ayanides.cloud/
            siteMonitor: https://pihole.ayanides.cloud/
            description: Manage internal DNS
            icon: pi-hole.png
        - Cloudflare:
            href: https://dash.cloudflare.com/0a3e510d8afc4bc60462b08165725b26/
            siteMonitor: https://dash.cloudflare.com/0a3e510d8afc4bc60462b08165725b26/
            description: Manage external DNS
            icon: cloudflare.png
        - Tailscale:
            href: https://login.tailscale.com/admin/machines/
            siteMonitor: https://login.tailscale.com/admin/machines/
            description: VPN management
            icon: tailscale.png
    - Security: []
    - Storage: []

  widgets:
    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
    # Uncomment to enable Kubernetes integration
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - openmeteo:
        label: Lille
        latitude:  50.633331
        longitude: 3.06667
        timezone: Europe/Paris
        units: metric
        cache: 5

  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
  docker:
  settings:
    fiveColumns: true

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs

# resources:
#   requests:
#     memory: 10Mi
#     cpu: 10m
#   limits:
#     memory: 200Mi
#     cpu: 500m