fullnameOverride: blackbox-exporter-external
# resources:
#   requests:
#     cpu: 23m
#     memory: 105M
#   limits:
#     memory: 105M

serviceMonitor:
  enabled: true
  selfMonitor:
    enabled: true
    interval: 1m
  defaults:
    interval: 1m
  targets:
    - name: ctfd
      url: https://ctfd.ayanides.cloud
      hostname: ctfd.ayanides.cloud
    - name: ovh-certificate-api
      url: https://ovh-certificate-api.ayanides.cloud
      hostname: ovh-certificate-api.ayanides.cloud
    - name: yopass
      url: https://yopass.ayanides.cloud
      hostname: yopass.ayanides.cloud
    - name: stirling-pdf
      url: https://stirling-pdf.ayanides.cloud
      hostname: stirling-pdf.ayanides.cloud

prometheusRule:
  enabled: true
  rules:
    - alert: BlackboxProbeFailed
      expr: probe_success == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: "Blackbox probe failed (instance {{ $labels.target }}\n VALUE = {{ $value }}"
    - alert: BlackboxProbeHttpFailure
      expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
      for: 5m
      labels:
        severity: critical
      annotations:
        message: "Blackbox probe HTTP failure (instance {{ $labels.target }})\n VALUE = {{ $value }}"
    - alert: BlackboxSlowProbe
      expr: avg_over_time(probe_duration_seconds[1m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        message: "Blackbox slow probe (target {{ $labels.target }})\n VALUE = {{ $value }}"
    - alert: BlackboxProbeSlowHttp
      expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        message: "Blackbox probe slow HTTP (instance {{ $labels.target }})\n VALUE = {{ $value }}"
    - alert: BlackboxProbeSlowPing
      expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        message: "Blackbox probe slow ping (instance {{ $labels.target }})\n  VALUE = {{ $value }}"
    - alert: BlackboxSslCertificateWillExpireSoon
      expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
      for: 5m
      labels:
        severity: warning
      annotations:
        message: "Blackbox SSL certificate will expire soon in 30 days (instance {{ $labels.target }})\n VALUE = {{ $value }}"
    - alert: BlackboxSslCertificateWillExpireSoon
      expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
      for: 5m
      labels:
        severity: critical
      annotations:
        message: "Blackbox SSL certificate will expire in less than 3 days (instance {{ $labels.target }})\n VALUE = {{ $value }}"
    - alert: BlackboxSslCertificateExpired
      expr: probe_ssl_earliest_cert_expiry - time() <= 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: "Blackbox SSL certificate expired (instance {{ $labels.target }})\n  VALUE = {{ $value }}"

dnsConfig:
  nameservers:
    - 1.0.0.1
dnsPolicy: "None"
