{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fastapi-profiling-example.fullname" . }}
  labels:
    {{- include "fastapi-profiling-example.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: {{ .Values.service.portName }}
    interval: 1m
    scrapeTimeout: 30s
    honorLabels: true
    path: /
    scheme: http
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "fastapi-profiling-example.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
{{- end }}