apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: longhorn-gcp-credentials

---

apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: s3://vault-infra-snapshot@us/
