applications:
  opentelemetry-operator:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: monitoring
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        chart: opentelemetry-operator
        targetRevision: 0.71.1
        helm:
          valueFiles:
          - $values/monitoring/opentelemetry/opentelemetry-operator/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true


  opentelemetry-collector:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: monitoring
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    source:
      repoURL: git@github.com:thibaultserti/kubernetes.git
      path: monitoring/opentelemetry/opentelemetry-collector
    ignoreDifferences:
      - group: opentelemetry.io
        kind: OpenTelemetryCollector
        jqPathExpressions:
          - .spec.config
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
