applications:
  robusta:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: monitoring
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: https://robusta-charts.storage.googleapis.com
        chart: robusta
        targetRevision: 0.17.0
        helm:
          valueFiles:
          - $values/monitoring/robusta/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
