applications:
  sloth:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: monitoring
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: https://slok.github.io/sloth
        chart: sloth
        targetRevision: 0.7.0
        helm:
          valueFiles:
          - $values/monitoring/sloth/sloth/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true


  slos:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: monitoring
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    sources:
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        path: monitoring/sloth/slos
        helm:
          valueFiles:
          - values.yaml
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
