api:
  logging: false # enable debug API access logging, sets logLevel to debug

rest:
  enabled: false

metrics:
  enabled: false

profiling:
  enabled: false


target:
  loki:
    host: "http://loki.monitoring:3100"
    skipTLS: true
    path: "/loki/api/v1/push"
    sources:
      - loki

monitoring:
  enabled: true
  plugins:
    kyverno: true


ui:
  enabled: true

  clusterName: belt

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: kyverno.ayanides.cloud
        paths:
          - path: /
            pathType: Prefix

  logSize: 200
  displayMode: dark
  views:
    dashboard:
      policyReports: true
      clusterPolicyReports: true
    logs: true # also remove the UI as target of policy reporter
    policyReports: true
    clusterPolicyReports: true
    kyvernoPolicies: true
    kyvernoVerifyImages: true
  plugins:
    kyverno: true

kyvernoPlugin:
  enabled: true
