apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlp
spec:
  mode: deployment
  ports:
    # - name: loki
    #   port: 3500
    #   protocol: TCP
  ingress:
    type: ingress
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostname: otlp.ayanides.cloud
    tls:
      - secretName: otlp-collector-tls
        hosts:
          - otlp.ayanides.cloud
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
