apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlp
spec:
  mode: deployment
  ports:
    - name: loki
      port: 3500
      protocol: TCP
  config: |
    receivers:
      loki:
        protocols:
          http:
        use_incoming_timestamp: true

    processors:
      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: container
          - action: insert
            key: loki.format
            value: raw
    exporters:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push

    service:
      pipelines:
        logs:
          receivers: [loki]
          processors: [attributes]
          exporters: [loki]
