apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otlp-collector
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/name: opentelemetry-collector
  endpoints:
    - port: prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
