apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: otel-collector
      app.kubernetes.io/name: otel-collector
  endpoints:
    - port: prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
