---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.default_issuer_name_staging }}
spec:
  acme:
    server: {{ .Values.server_staging }}
    email: {{ .Values.acme_registration_email }}
    privateKeySecretRef:
      name: {{ .Values.secret_reference_staging }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.default_issuer_name_prod }}
spec:
  acme:
    server: {{ .Values.server_prod }}
    email: {{ .Values.acme_registration_email }}
    privateKeySecretRef:
      name: {{ .Values.secret_reference_prod }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: {{ .Values.traefik_namespace }}
spec:
  secretName: wildcard-cert
  dnsNames:
    - "ayanides.cloud"
    - "*.ayanides.cloud"
  issuerRef:
    name: {{ .Values.default_issuer_name_prod }}
    kind: ClusterIssuer