applications:
  # ARGOCD
  argocd:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: argocd
#      argocd.argoproj.io/compare-options: ServerSideDiff=true
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: 7.4.5
        helm:
          valueFiles:
          - $values/argocd/argocd/values.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    ignoreDifferences:
      - kind: Secret
        name: argocd-secret
        namespace: argocd
        jsonPointers:
          - /data
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true

  argocd-apps:
    namespace: argocd
    additionalAnnotations:
      notifications.argoproj.io/subscribe.grafana: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argocd-apps
        targetRevision: 2.0.0
        helm:
          valueFiles:
          - $values/argocd/argocd-apps/base/argocd/0_project.yaml
          - $values/argocd/argocd-apps/base/argocd/argocd.yaml
          - $values/argocd/argocd-apps/base/system/0_project.yaml
          - $values/argocd/argocd-apps/base/system/cilium.yaml
          - $values/argocd/argocd-apps/base/system/longhorn.yaml
          - $values/argocd/argocd-apps/base/system/ksm.yaml
          - $values/argocd/argocd-apps/base/system/kured.yaml
          - $values/argocd/argocd-apps/base/system/etcd-defrag.yaml
          - $values/argocd/argocd-apps/base/kyverno/0_project.yaml
          - $values/argocd/argocd-apps/base/kyverno/kyverno.yaml
          - $values/argocd/argocd-apps/base/traefik/0_project.yaml
          - $values/argocd/argocd-apps/base/traefik/traefik.yaml
          - $values/argocd/argocd-apps/base/traefik/cert-manager.yaml
          - $values/argocd/argocd-apps/base/traefik/external-dns.yaml
          - $values/argocd/argocd-apps/base/vault/0_project.yaml
          - $values/argocd/argocd-apps/base/vault/vault.yaml
          - $values/argocd/argocd-apps/base/traefik/traefik.yaml
          - $values/argocd/argocd-apps/base/traefik/cert-manager.yaml
          - $values/argocd/argocd-apps/monitoring/0_project.yaml
          - $values/argocd/argocd-apps/monitoring/prom-crds.yaml
          - $values/argocd/argocd-apps/monitoring/falco.yaml
          - $values/argocd/argocd-apps/monitoring/grafana.yaml
          - $values/argocd/argocd-apps/monitoring/kepler.yaml
          - $values/argocd/argocd-apps/monitoring/kuma.yaml
          - $values/argocd/argocd-apps/monitoring/locust.yaml
          - $values/argocd/argocd-apps/monitoring/loki.yaml
          - $values/argocd/argocd-apps/monitoring/otel.yaml
          - $values/argocd/argocd-apps/monitoring/pyroscope.yaml
          - $values/argocd/argocd-apps/monitoring/robusta.yaml
          - $values/argocd/argocd-apps/monitoring/sloth.yaml
          - $values/argocd/argocd-apps/monitoring/tempo.yaml
          - $values/argocd/argocd-apps/monitoring/victoriametrics.yaml
          - $values/argocd/argocd-apps/monitoring/exporters.yaml
          - $values/argocd/argocd-apps/db/minio/0_project.yaml
          - $values/argocd/argocd-apps/db/minio/minio.yaml
          - $values/argocd/argocd-apps/db/redis/0_project.yaml
          - $values/argocd/argocd-apps/db/redis/redis.yaml
          - $values/argocd/argocd-apps/apps/0_project.yaml
          - $values/argocd/argocd-apps/apps/buzzer.yaml
          - $values/argocd/argocd-apps/apps/challenges.yaml
          # - $values/argocd/argocd-apps/apps/ctfd.yaml
          - $values/argocd/argocd-apps/apps/homepage.yaml
          - $values/argocd/argocd-apps/apps/stirling-pdf.yaml
          - $values/argocd/argocd-apps/apps/yopass.yaml
      - repoURL: git@github.com:thibaultserti/kubernetes.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          goldilocks.fairwinds.com/enabled: "true"
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
