app:
  replicaCount: 1

  podAnnotations:
    instrumentation.opentelemetry.io/inject-python: "monitoring/instrumentation-python"
  #   policy.cilium.io/proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>,<Ingress/8000/TCP/HTTP>"

  image:
    repository: ghcr.io/thibaultserti/ovh-certificate-api
    pullPolicy: Always
    tag: 1.1.0

  serviceAccount:
    create: true

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: ovh-certificate-api.ayanides.cloud
        paths:
          - path: /
            pathType: Prefix


  autoscaling:
    enabled: false


  env:
    - name: OVH_APPLICATION_KEY
      valueFrom:
        secretKeyRef:
          name: ovh-certificate-api-secret
          key: ovh_application_key
    - name: OVH_APPLICATION_SECRET
      valueFrom:
        secretKeyRef:
          name: ovh-certificate-api-secret
          key: ovh_application_secret
    - name: OVH_CONSUMER_KEY
      valueFrom:
        secretKeyRef:
          name: ovh-certificate-api-secret
          key: ovh_consumer_key
    - name: DOMAIN_NAME
      valueFrom:
        secretKeyRef:
          name: ovh-certificate-api-secret
          key: domain_name

  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities: {}
    readOnlyRootFilesystem: false
    runAsNonRoot: false


  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 256M
  #   limits:
  #     memory: 256M


  extraSecretMounts:
    - name: secrets-store-inline
      mountPath: /mnt/secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: ovh-certificate-api

  extraVolumeMounts:
    - name: accounts
      mountPath: /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/154e2bb6d054490d09ce64c3672aed7f

  extraVolumes:
    - name: accounts
      secret:
        secretName: "ovh-certificate-api-acme-accounts"
