config:
  extraEnv:
    - name: DISCORD_WEBHOOKURL
      valueFrom:
        secretKeyRef:
          name: falcosidekick-secret
          key: DISCORD_WEBHOOKURL

  policyreport:
    enabled: true

# resources:
#   requests:
#     cpu: 15m
#     memory: 105M
#   limits:
#     memory: 105M

webui:
  enabled: true
  replicaCount: 2
  # -- User in format <login>:<password>
  user: "admin:admin"
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 105M
  #   limits:
  #     memory: 105M
  redis:
    storageEnabled: true
    storageSize: "1Gi"
    storageClass: longhorn
    # resources:
    #   requests:
    #     cpu: 15m
    #     memory: 164M
    #   limits:
    #     memory: 164M

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: eBPF runtime security for Kubernetes
      gethomepage.dev/pod-selector: >-
            app.kubernetes.io/name in (
                falco,
                falcosidekick
            )
      gethomepage.dev/group: Security
      gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/thibaultserti/kubernetes@main/services/homepage/icons/falco.png
      gethomepage.dev/name: Falco
      gethomepage.dev/weight: "20"
    hosts:
      - host: falco.ayanides.cloud
        paths:
        - path: /

extraVolumeMounts:
  - mountPath: /mnt/secrets-store
    name: secrets-store-inline

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: falcosidekick