---
vaultAddress: "https://vault.ayanides.cloud"

secretsStores:
  - name: grafana
    namespace: monitoring
    roleName: grafana
    secrets:
      grafana-secret:
        - kubernetesSecretKey: admin-user
          vaultSecretPath: secrets/data/grafana
          vaultSecretKey: user
        - kubernetesSecretKey: admin-password
          vaultSecretPath: secrets/data/grafana
          vaultSecretKey: password
  - name: argocd-notifications-controller
    namespace: argocd
    roleName: argocd-notifications-controller
    secrets:
      argocd-notifications-secret:
        - kubernetesSecretKey: discord-url
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: discord_url
        - kubernetesSecretKey: grafana-api-key
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: grafana_api_key
        - kubernetesSecretKey: grafana-url
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: grafana_url
  - name: alertmanager
    namespace: monitoring
    roleName: prometheus-stack-kube-prom-alertmanager
    secrets:
      alertmanager-secret:
        - kubernetesSecretKey: url_critical
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_critical
        - kubernetesSecretKey: url_warning
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_warning
        - kubernetesSecretKey: url_low
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_low
  - name: pihole-exporter
    namespace: monitoring
    roleName: pihole-exporter
    secrets:
      pihole-exporter-secret:
        - kubernetesSecretKey: hostname
          vaultSecretPath: secrets/data/pihole-exporter
          vaultSecretKey: hostname
        - kubernetesSecretKey: api_token
          vaultSecretPath: secrets/data/pihole-exporter
          vaultSecretKey: api_token
  - name: robusta
    namespace: monitoring
    roleName: robusta-runner-service-account
    secrets:
      robusta-secret:
        - kubernetesSecretKey: signing_key
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: signing_key
        - kubernetesSecretKey: account_id
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: account_id
        - kubernetesSecretKey: discord_url
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: discord_url
        - kubernetesSecretKey: robusta_ui_token
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: robusta_ui_token
      robusta-auth-config-secret:
        - kubernetesSecretKey: prv
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: rsa_private
        - kubernetesSecretKey: pub
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: rsa_public
  - name: minio
    namespace: minio
    roleName: minio
    secrets:
      minio-secret:
        - kubernetesSecretKey: root-user
          vaultSecretPath: secrets/data/minio
          vaultSecretKey: user
        - kubernetesSecretKey: root-password
          vaultSecretPath: secrets/data/minio
          vaultSecretKey: password
  - name: loki
    namespace: monitoring
    roleName: loki
    secrets:
      loki-bucket-secret:
        - kubernetesSecretKey: S3_LOKI_ACCESS_KEY_ID
          vaultSecretPath: secrets/data/loki
          vaultSecretKey: s3_access_key_id
        - kubernetesSecretKey: S3_LOKI_SECRET_ACCESS_KEY
          vaultSecretPath: secrets/data/loki
          vaultSecretKey: s3_secret_access_key
  - name: tempo
    namespace: monitoring
    roleName: tempo
    secrets:
      tempo-bucket-secret:
        - kubernetesSecretKey: S3_TEMPO_ACCESS_KEY_ID
          vaultSecretPath: secrets/data/tempo
          vaultSecretKey: s3_access_key_id
        - kubernetesSecretKey: S3_TEMPO_SECRET_ACCESS_KEY
          vaultSecretPath: secrets/data/tempo
          vaultSecretKey: s3_secret_access_key
  - name: vault-snapshot
    namespace: vault
    roleName: vault-snapshot
    secrets:
      vault-snapshot-agent-token:
        - kubernetesSecretKey: VAULT_APPROLE_ROLE_ID
          vaultSecretPath: secrets/data/vault-snapshot
          vaultSecretKey: vault_approle_role_id
        - kubernetesSecretKey: VAULT_APPROLE_SECRET_ID
          vaultSecretPath: secrets/data/vault-snapshot
          vaultSecretKey: vault_approle_secret_id
      vault-snapshot-gcs:
        - kubernetesSecretKey: GOOGLE_APPLICATION_CREDENTIALS
          vaultSecretPath: secrets/data/vault-snapshot
          vaultSecretKey: google_application_credentials
