---
vaultAddress: "https://vault.ayanides.cloud"

secretsStores:
  - name: grafana
    namespace: monitoring
    roleName: grafana
    secrets:
      grafana-secret:
        - kubernetesSecretKey: admin-user
          vaultSecretPath: secrets/data/grafana
          vaultSecretKey: user
        - kubernetesSecretKey: admin-password
          vaultSecretPath: secrets/data/grafana
          vaultSecretKey: password
  - name: argocd-notifications-controller
    namespace: argocd
    roleName: argocd-notifications-controller
    secrets:
      argocd-notifications-secret:
        - kubernetesSecretKey: discord-url
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: discord_url
        - kubernetesSecretKey: grafana-api-key
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: grafana_api_key
        - kubernetesSecretKey: grafana-url
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: grafana_url
  - name: alertmanager
    namespace: monitoring
    roleName: prometheus-stack-kube-prom-alertmanager
    secrets:
      alertmanager-secret:
        - kubernetesSecretKey: url_critical
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_critical
        - kubernetesSecretKey: url_warning
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_warning
        - kubernetesSecretKey: url_low
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_low
  - name: pihole-exporter
    namespace: monitoring
    roleName: pihole-exporter
    secrets:
      pihole-exporter-secret:
        - kubernetesSecretKey: hostname
          vaultSecretPath: secrets/data/pihole-exporter
          vaultSecretKey: hostname
        - kubernetesSecretKey: api_token
          vaultSecretPath: secrets/data/pihole-exporter
          vaultSecretKey: api_token
  - name: robusta
    namespace: monitoring
    roleName: robusta-runner-service-account
    secrets:
      robusta-secret:
        - kubernetesSecretKey: signing_key
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: signing_key
        - kubernetesSecretKey: account_id
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: account_id
        - kubernetesSecretKey: discord_url
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: discord_url
        - kubernetesSecretKey: robusta_ui_token
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: robusta_ui_token
      robusta-auth-config-secret:
        - kubernetesSecretKey: prv
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: rsa_private
        - kubernetesSecretKey: pub
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: rsa_public