---
vaultAddress: "https://vault.ayanides.cloud"

secretsStores:
  - name: grafana
    namespace: monitoring
    roleName: grafana
    secrets:
      grafana-secret:
        - kubernetesSecretKey: admin-user
          vaultSecretPath: secrets/data/grafana
          vaultSecretKey: user
        - kubernetesSecretKey: admin-password
          vaultSecretPath: secrets/data/grafana
          vaultSecretKey: password
  - name: argocd-notifications-controller
    namespace: argocd
    roleName: argocd-notifications-controller
    secrets:
      argocd-notifications-secret:
        - kubernetesSecretKey: discord-url
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: discord_url
        - kubernetesSecretKey: grafana-api-key
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: grafana_api_key
        - kubernetesSecretKey: grafana-url
          vaultSecretPath: secrets/data/argocd/notifications
          vaultSecretKey: grafana_url
  - name: alertmanager
    namespace: monitoring
    roleName: prometheus-stack-kube-prom-alertmanager
    secrets:
      alertmanager-secret:
        - kubernetesSecretKey: url_critical
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_critical
        - kubernetesSecretKey: url_warning
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_warning
        - kubernetesSecretKey: url_low
          vaultSecretPath: secrets/data/alertmanager
          vaultSecretKey: url_low
  - name: pihole-exporter
    namespace: monitoring
    roleName: pihole-exporter
    secrets:
      pihole-exporter-secret:
        - kubernetesSecretKey: hostname
          vaultSecretPath: secrets/data/pihole-exporter
          vaultSecretKey: hostname
        - kubernetesSecretKey: api_token
          vaultSecretPath: secrets/data/pihole-exporter
          vaultSecretKey: api_token
  - name: robusta
    namespace: monitoring
    roleName: robusta-runner-service-account
    secrets:
      robusta-secret:
        - kubernetesSecretKey: signing_key
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: signing_key
        - kubernetesSecretKey: account_id
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: account_id
        - kubernetesSecretKey: discord_url
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: discord_url
        - kubernetesSecretKey: robusta_ui_token
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: robusta_ui_token
      robusta-auth-config-secret:
        - kubernetesSecretKey: prv
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: rsa_private
        - kubernetesSecretKey: pub
          vaultSecretPath: secrets/data/robusta
          vaultSecretKey: rsa_public
  - name: minio
    namespace: minio
    roleName: minio
    secrets:
      minio-secret:
        - kubernetesSecretKey: root-user
          vaultSecretPath: secrets/data/minio
          vaultSecretKey: user
        - kubernetesSecretKey: root-password
          vaultSecretPath: secrets/data/minio
          vaultSecretKey: password
  - name: loki
    namespace: monitoring
    roleName: loki
    secrets:
      loki-bucket-secret:
        - kubernetesSecretKey: S3_LOKI_ACCESS_KEY_ID
          vaultSecretPath: secrets/data/loki
          vaultSecretKey: s3_access_key_id
        - kubernetesSecretKey: S3_LOKI_SECRET_ACCESS_KEY
          vaultSecretPath: secrets/data/loki
          vaultSecretKey: s3_secret_access_key
  - name: tempo
    namespace: monitoring
    roleName: tempo
    secrets:
      tempo-bucket-secret:
        - kubernetesSecretKey: S3_TEMPO_ACCESS_KEY_ID
          vaultSecretPath: secrets/data/tempo
          vaultSecretKey: s3_access_key_id
        - kubernetesSecretKey: S3_TEMPO_SECRET_ACCESS_KEY
          vaultSecretPath: secrets/data/tempo
          vaultSecretKey: s3_secret_access_key
  - name: mimir
    namespace: monitoring
    roleName: mimir
    secrets:
      mimir-bucket-secret:
        - kubernetesSecretKey: S3_MIMIR_ACCESS_KEY_ID
          vaultSecretPath: secrets/data/mimir
          vaultSecretKey: s3_access_key_id
        - kubernetesSecretKey: S3_MIMIR_SECRET_ACCESS_KEY
          vaultSecretPath: secrets/data/mimir
          vaultSecretKey: s3_secret_access_key
  - name: thanos
    namespace: monitoring
    roleName: thanos-query
    secrets:
      thanos-objstore-secret:
        - kubernetesSecretKey: objstore.yml
          vaultSecretPath: secrets/data/thanos
          vaultSecretKey: objstoreConfig
      thanos-tracing-secret:
        - kubernetesSecretKey: tracing.yml
          vaultSecretPath: secrets/data/thanos
          vaultSecretKey: tracingConfig
  - name: longhorn
    namespace: longhorn-system
    roleName: longhorn-service-account
    secrets:
      longhorn-gcp-credentials:
        - kubernetesSecretKey: AWS_ACCESS_KEY_ID
          vaultSecretPath: secrets/data/longhorn
          vaultSecretKey: aws_access_key_id
        - kubernetesSecretKey: AWS_SECRET_ACCESS_KEY
          vaultSecretPath: secrets/data/longhorn
          vaultSecretKey: aws_secret_access_key
        - kubernetesSecretKey: AWS_ENDPOINTS
          vaultSecretPath: secrets/data/longhorn
          vaultSecretKey: aws_endpoints
  - name: falcosidekick
    namespace: falco
    roleName: falcosidekick
    secrets:
      falcosidekick-secret:
        - kubernetesSecretKey: DISCORD_WEBHOOKURL
          vaultSecretPath: secrets/data/falco
          vaultSecretKey: discord_url
  - name: ctfd
    namespace: ctfd
    roleName: ctfd
    secrets:
      ctfd-secret:
        - kubernetesSecretKey: SECRET_KEY
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: secret_key
        - kubernetesSecretKey: S3_CTFD_ACCESS_KEY_ID
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: s3_access_key_id
        - kubernetesSecretKey: S3_CTFD_SECRET_ACCESS_KEY
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: s3_secret_access_key
        - kubernetesSecretKey: AWS_S3_BUCKET
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: s3_bucket
        - kubernetesSecretKey: AWS_S3_ENDPOINT_URL
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: s3_endpoint_url
        - kubernetesSecretKey: MAIL_USERNAME
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: smtp_user
        - kubernetesSecretKey: MAIL_PASSWORD
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: smtp_password
        - kubernetesSecretKey: MAIL_SERVER
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: smtp_domain
        - kubernetesSecretKey: MAIL_PORT
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: smtp_port
        - kubernetesSecretKey: MAIL_USEAUTH
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: smtp_useauth
        - kubernetesSecretKey: MAIL_TLS
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: smtp_tls
        - kubernetesSecretKey: MAILFROM_ADDR
          vaultSecretPath: secrets/data/ctfd/ctfd
          vaultSecretKey: smtp_fromaddr

  - name: ctfd-mariadb
    namespace: ctfd
    roleName: ctfd-mariadb
    secrets:
      ctfd-mariadb-secret:
        - kubernetesSecretKey: mariadb-replication-password
          vaultSecretPath: secrets/data/ctfd/mariadb
          vaultSecretKey: mariadb-replication-password
        - kubernetesSecretKey: mariadb-password
          vaultSecretPath: secrets/data/ctfd/mariadb
          vaultSecretKey: mariadb-password
        - kubernetesSecretKey: mariadb-root-password
          vaultSecretPath: secrets/data/ctfd/mariadb
          vaultSecretKey: mariadb-root-password
  - name: ctfd-redis
    namespace: ctfd
    roleName: ctfd-redis
    secrets:
      ctfd-redis-secret:
        - kubernetesSecretKey: redis-password
          vaultSecretPath: secrets/data/ctfd/redis
          vaultSecretKey: redis-password