serviceMonitor:
  enabled: true
  interval: 1m

# resources:
#   requests:
#     cpu: 15m
#     memory: 105M
#   limits:
#     memory: 105M

grafanaDashboard:
  enabled: false
scc:
  create: false

prometheusRules:
  enabled: true
  alerts:
    critical:
      enabled: false
