clusterName: "teleport.ayanides.cloud"


authentication:
  # Default authentication type. Possible values are 'local' and 'github' for OSS, plus 'oidc' and 'saml' for Enterprise.
  type: github

  # Second factor requirements for users of the Teleport cluster.
  # Controls the `auth_config.authentication.second_factor` field in `teleport.yaml`.
  # Possible values are 'off', 'on', 'otp', 'optional' and 'webauthn'.
  #
  # WARNING:
  #   If you set `publicAddr` for users to access the cluster under a domain different
  #   to clusterName you must manually set the webauthn Relying
  #   Party Identifier (RP ID) - https://www.w3.org/TR/webauthn-2/#relying-party-identifier
  #   If you don't, RP ID will default to `clusterName` and users will fail
  #   to register second factors.
  #
  #   You can do this by setting the value
  #   `auth.teleportConfig.auth_service.authentication.webauthn.rp_id`.
  #
  #   RP ID must be both a valid domain, and part of the full domain users are connecting to.
  #   For example, if users are accessing the cluster with the domain
  #   "teleport.example.com", RP ID can be "teleport.example.com" or "example.com".
  #
  #   Changing the RP ID will invalidate all already registered webauthn second factors.
  secondFactor: "off"


teleportConfig:
  tracing_service:
    enabled: yes
    exporter_url: grpc://otel-collector.monitoring:4317
    sampling_rate_per_million: 1000000

proxyListenerMode: multiplex


auth:
  resources:
    requests:
      cpu: 11m
      memory: 110M
    limits:
      memory: 110M

operator:
  enabled: true
  resources:
    requests:
      cpu: 11m
      memory: 64M
    limits:
      memory: 64M

proxy:
  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      memory: 105M

podSecurityPolicy:
  enabled: false

chartMode: standalone

podMonitor:
  enabled: true

persistence:
  enabled: true
  volumeSize: 10Gi
  storageClassName: default

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.101

highAvailability:
  replicaCount: 1
  certManager:
    enabled: true
    addCommonName: true
    issuerKind: ClusterIssuer
    issuerName: letsencrypt-prod

ingress:
  enabled: false
