installCRDs: true

resources:
  requests:
    cpu: 15m
    memory: 105Mi
  limits:
    cpu: 15m
    memory: 105Mi

webhook:
  resources:
    requests:
      cpu: 15m
      memory: 105Mi
    limits:
      cpu: 15m
      memory: 105Mi

cainjector:
  resources:
    requests:
      cpu: 15m
      memory: 105Mi
    limits:
      cpu: 15m
      memory: 105Mi