ingress:
  enabled: true
  className: traefik
  hosts:
    - host: yopass.ayanides.cloud
      paths:
        - path: /
          pathType: Prefix

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"


metrics:
  enabled: true

database:
  type: redis
  dsn: redis://redis-master.redis:6379/0


resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    memory: 105M

redis:
  enabled: false


memcached:
  enabled: false
