metrics:
  enabled: true


securityContext:
  pod:
    fsGroup: 100
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 100
  container:
    allowPrivilegeEscalation: false

# resources:
#   requests:
#     cpu: 11m
#     memory: 79M
#   limits:
#     memory: 79M

# commonPlugins:
#   gitRepo:
#     resources:
#       requests:
#         cpu: 11m
#         memory: 53M
#       limits:
#         memory: 53M